### ISSUE TITLE
Unable to import solution

### ISSUE THREAD

**Issue by drivardxrm** [bthompson-365/PCF-Metadata#1]
Hi, when I try to import the solution contained in the repo, I get this error.

Import   Solution Failed: CustomControls with Name hdn.SelectView Import Solution   Failed with following error: Publisher prefix houdini for this control   hdn.SelectView does not match the prefix hdn for the solution with Id   7eccd0db-0846-4a1d-a1dc-406cec09d8be.
--

Does anyone else have had this issue?

**Comment by bthompson-365** [comment]
That's going to be my fault for copying stuff and not testing the managed solution. I will redeploy everything and export it tomorrow.

**Comment by drivardxrm** [comment]
Thanks ;)

Great stuff BTW!

**Comment by bthompson-365** [comment]
Sorry for the delay but a working version has now been uploaded.
